let title = "E-Waste";
let articles = {
    "Definition": "definition",
    "Why it Matters": "matters",
    "Effects": "effects",
}
articlesContent = [
    "Electronic waste, universally known as e-waste, encompasses the complete spectrum of discarded, obsolete, or end-of-life electrical and electronic equipment including computers, servers, smartphones, tablets, networking equipment, consumer electronics, and various digital devices. This category represents one of the most rapidly expanding waste streams in the modern world, with global generation rates increasing by approximately 20% annually as technology adoption accelerates worldwide and device replacement cycles shorten due to rapid technological advancement and planned obsolescence strategies. \n" +
    "\n" +
    "E-waste presents a complex materials challenge because modern electronic devices contain intricate combinations of valuable recoverable materials alongside potentially hazardous substances requiring specialized handling. Valuable components include precious metals such as gold, silver, platinum, and palladium, along with industrially important materials like copper, aluminum, and increasingly scarce rare earth elements essential for modern electronics manufacturing. These valuable materials often represent significant economic value, with estimates suggesting that the raw materials in discarded electronics are worth billions of dollars annually. \n" +
    "\n" +
    "Simultaneously, these devices contain numerous hazardous substances including lead solder, mercury switches, cadmium batteries, brominated flame retardants, and various toxic compounds used in circuit boards, displays, and protective coatings. The complexity of modern electronics means that safe e-waste processing requires sophisticated separation and treatment technologies to recover valuable materials while safely neutralizing or containing harmful substances. The global scale has reached crisis proportions, with over 50 million tons generated annually worldwide, and this figure continues growing as digital technology penetration increases globally. ",

    "E-waste represents one of the most pressing environmental and economic challenges of the digital age, with far-reaching implications for global sustainability, resource security, and environmental justice. Environmental impacts are severe and multifaceted, extending far beyond simple waste disposal concerns, as inappropriate disposal in conventional landfills allows toxic heavy metals and persistent organic compounds to leach into soil and groundwater systems, creating long-term contamination affecting local ecosystems and potentially threatening human health through contaminated water supplies and food chains. Incineration releases harmful chemicals and particulates into the atmosphere, contributing to air pollution and climate change while exposing nearby communities to toxic emissions. \n" +
    "\n" +
    "Economic implications are equally significant and growing more critical as global demand for electronic devices continues expanding, with e-waste containing substantial quantities of precious metals, rare earth elements, and other valuable materials that are expensive and environmentally destructive to extract through traditional mining operations. When electronic devices are discarded rather than properly recycled, these valuable resources are permanently lost, increasing demand for new mining operations and perpetuating environmental destruction in resource extraction regions. Resource scarcity concerns intensify as global electronics demand outpaces sustainable supply chains for critical materials, with many components depending on rare earth elements and precious metals from geographically concentrated and politically unstable regions. \n" +
    "\n" +
    "Social justice dimensions reveal troubling patterns where developed nations export electronic waste to developing countries with less stringent environmental regulations and labor protections, creating informal e-waste recycling operations that expose workers to dangerous conditions without proper safety equipment, training, or environmental safeguards. This global environmental justice crisis disproportionately affects economically disadvantaged communities while allowing wealthier nations to externalize the true costs of their consumption patterns. The rapid pace of technological change and deliberately shortened product lifecycles exacerbate these problems by accelerating replacement cycles and increasing overall waste generation rates. ",

    "Neuromorphic computing technology has the potential to fundamentally transform global e-waste generation patterns through multiple interconnected mechanisms, with the exceptional energy efficiency potentially extending device operational lifespans by dramatically reducing power consumption and heat generation, two primary factors contributing to hardware component degradation and premature device failure. Lower operating temperatures and reduced electrical stress on components could potentially double or triple device lifespans for certain applications, significantly reducing replacement frequency and associated e-waste generation. Adaptive learning capabilities could maintain device performance relevance far longer than traditional systems, as neuromorphic devices could learn new functions and adapt to changing requirements without hardware replacement. \n" +
    "\n" +
    "The ultra-low power consumption characteristics could revolutionize battery-powered device categories by extending operational times between charges by orders of magnitude, significantly reducing battery replacement frequency and extending overall device lifespans since battery degradation is often a primary driver of complete device replacement. The inherent fault tolerance and distributed processing nature of neuromorphic systems could result in more robust devices that continue functioning even when individual components fail, further extending operational lifespans and reducing premature replacements due to component failures. \n" +
    "\n" +
    "However, the transition period presents challenges as specialized materials, novel manufacturing processes, and unique architectural approaches may create entirely new categories of electronic waste that existing recycling infrastructure cannot effectively handle, requiring substantial modifications to current e-waste processing facilities. The adoption transition could temporarily increase global e-waste generation as organizations replace existing systems with neuromorphic alternatives, creating short-term spikes in waste volumes. Manufacturing complexity during early commercialization might result in higher defect rates and developmental waste, though these issues should diminish as technology matures. Long-term projections suggest substantial e-waste reduction through improved device longevity, reduced power consumption, and adaptive capabilities, but success will depend on sustainable design principles, responsible manufacturing practices, and development of appropriate recycling infrastructure for neuromorphic technologies. "
]

const pages = ["Overview", "Description", "E-Waste"]
